(lang dune 3.10)

(name Ocaml)

(generate_opam_files true)

(package
 (name Ocaml)
 (synopsis "An OCaml implementation of the B2T2 table benchmark")
 (description "An immutable, schema-checked core for B2T2 tables.")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
